// Trigger helper functions for local writes (crsql_after_insert/update/delete)
//
// These functions are called from triggers generated by crsql_as_crr().
// They implement the Rust/C trigger helper semantics so that databases can be
// modified cross-implementation.
//
// Reference:
// - core/rs/core/src/local_writes/after_{insert,update,delete}.rs
// - core/rs/core/src/tableinfo.rs (SQL templates for clock writes)

const std = @import("std");
const api = @import("../ffi/api.zig");
const site_identity = @import("../site_identity.zig");
const compare_values = @import("../compare_values.zig");

const MAX_SQL_BUF = 4096;
const MAX_ERR_BUF = 512;

// Thread-local error buffer for diagnostics
threadlocal var last_error_buf: [MAX_ERR_BUF]u8 = undefined;
threadlocal var last_error_len: usize = 0;

fn setLastError(msg: []const u8) void {
    const len = @min(msg.len, MAX_ERR_BUF - 1);
    @memcpy(last_error_buf[0..len], msg[0..len]);
    last_error_len = len;
    last_error_buf[len] = 0;
}

fn setLastErrorFmt(comptime fmt: []const u8, args: anytype) void {
    const msg = std.fmt.bufPrint(&last_error_buf, fmt, args) catch {
        setLastError("error formatting failed");
        return;
    };
    last_error_len = msg.len;
}

const ColumnInfo = struct {
    name: [128]u8,
    name_len: usize,
    pk_index: c_int,
};

const TableInfo = struct {
    columns: [64]ColumnInfo,
    count: usize,
    pk_count: usize,
    non_pk_count: usize,
};

fn getTableInfo(db: ?*api.sqlite3, table_name: []const u8) ?TableInfo {
    var info = TableInfo{
        .columns = [_]ColumnInfo{.{ .name = [_]u8{0} ** 128, .name_len = 0, .pk_index = 0 }} ** 64,
        .count = 0,
        .pk_count = 0,
        .non_pk_count = 0,
    };

    var pragma_buf: [256]u8 = undefined;
    var pragma_len: usize = 0;

    const prefix = "PRAGMA table_info(\"";
    @memcpy(pragma_buf[pragma_len .. pragma_len + prefix.len], prefix);
    pragma_len += prefix.len;

    if (table_name.len + pragma_len + 3 > pragma_buf.len) return null;
    @memcpy(pragma_buf[pragma_len .. pragma_len + table_name.len], table_name);
    pragma_len += table_name.len;

    @memcpy(pragma_buf[pragma_len .. pragma_len + 2], "\")");
    pragma_len += 2;
    pragma_buf[pragma_len] = 0;

    const pragma_sql: [*:0]const u8 = @ptrCast(&pragma_buf);

    var stmt: ?*api.sqlite3_stmt = null;
    const rc = api.prepare_v2(db, pragma_sql, -1, &stmt, null);
    if (rc != api.SQLITE_OK) {
        setLastErrorFmt("getTableInfo PRAGMA prepare failed for table {s}", .{table_name});
        return null;
    }
    defer _ = api.finalize(stmt);

    while (api.step(stmt) == api.SQLITE_ROW) {
        if (info.count >= 64) return null;

        const name_ptr = api.column_text(stmt, 1) orelse continue;
        const name_slice = std.mem.span(name_ptr);
        if (name_slice.len >= 128) return null;

        var col = &info.columns[info.count];
        @memcpy(col.name[0..name_slice.len], name_slice);
        col.name_len = name_slice.len;

        const pk_val = api.column_int64(stmt, 5);
        col.pk_index = @intCast(pk_val);
        if (col.pk_index > 0) {
            info.pk_count += 1;
        } else {
            info.non_pk_count += 1;
        }

        info.count += 1;
    }

    // Debug: log what we found
    if (info.count == 0) {
        setLastErrorFmt("getTableInfo found 0 columns for table {s}", .{table_name});
    }

    return info;
}

fn getPkColumnName(info: *const TableInfo, pk_order: usize) ?[]const u8 {
    // IMPORTANT: Iterate by index, not by value, to avoid returning slice into local copy
    for (0..info.count) |i| {
        const col = &info.columns[i];
        if (col.pk_index == @as(c_int, @intCast(pk_order))) {
            const result = col.name[0..col.name_len];
            // Debug: ensure we're returning a valid name
            if (result.len == 0) {
                setLastErrorFmt("getPkColumnName found empty name for pk_order={}", .{pk_order});
            }
            return result;
        }
    }
    // Debug: record which pk_order we couldn't find
    setLastErrorFmt("getPkColumnName: no column found with pk_index={} (have {} cols, {} pks)", .{ pk_order, info.count, info.pk_count });
    return null;
}

fn bindValue(stmt: ?*api.sqlite3_stmt, idx: c_int, val: *api.sqlite3_value) c_int {
    const val_type = api.value_type(val);
    return switch (val_type) {
        api.SQLITE_NULL => api.bind_null(stmt, idx),
        api.SQLITE_INTEGER => api.bind_int64(stmt, idx, api.value_int64(val)),
        api.SQLITE_FLOAT => api.bind_double(stmt, idx, api.value_double(val)),
        api.SQLITE_TEXT => blk: {
            const text_ptr = api.value_text(val);
            const len = api.value_bytes(val);
            if (text_ptr) |t| {
                break :blk api.bind_text(stmt, idx, t, len, api.getTransientDestructor());
            } else {
                break :blk api.bind_null(stmt, idx);
            }
        },
        api.SQLITE_BLOB => blk: {
            const blob_ptr = api.value_blob(val);
            const len = api.value_bytes(val);
            break :blk api.bind_blob(stmt, idx, blob_ptr, len, api.getTransientDestructor());
        },
        else => api.bind_null(stmt, idx),
    };
}

/// Lookup __crsql_key for pk tuple; create if missing.
/// Matches Rust/C `TableInfo.get_or_create_key_via_raw_values`.
fn getOrCreatePkKey(
    db: ?*api.sqlite3,
    table_name: []const u8,
    info: *const TableInfo,
    pk_values: []*api.sqlite3_value,
) ?i64 {
    if (db == null) {
        setLastError("db is null");
        return null;
    }

    // Debug: log what we have
    if (info.pk_count == 0) {
        setLastError("info.pk_count is 0");
        return null;
    }

    // Build a debug string of all columns and fail immediately to see column info
    var debug_buf: [512]u8 = undefined;
    var debug_len: usize = 0;
    for (info.columns[0..info.count]) |col| {
        const name_slice = col.name[0..col.name_len];
        const part = std.fmt.bufPrint(debug_buf[debug_len..], "{s}(pk={}),", .{ name_slice, col.pk_index }) catch break;
        debug_len += part.len;
    }

    // Debug info logged (we know cols are correct now)

    // SELECT __crsql_key FROM "{table}__crsql_pks" WHERE "pk1" IS ? AND "pk2" IS ? ...
    var select_buf: [MAX_SQL_BUF]u8 = undefined;
    var select_fbs = std.io.fixedBufferStream(&select_buf);
    const select_writer = select_fbs.writer();

    select_writer.print("SELECT __crsql_key FROM \"{s}__crsql_pks\" WHERE ", .{table_name}) catch {
        setLastError("failed to format SELECT SQL");
        return null;
    };

    var pk_order: usize = 1;
    var pk_written: usize = 0;
    var iteration: usize = 0;
    while (pk_written < info.pk_count) : (pk_order += 1) {
        iteration += 1;
        // DEBUG: Log each iteration
        if (iteration > 10) {
            setLastError("infinite loop protection");
            return null;
        }
        const col_name = getPkColumnName(info, pk_order) orelse {
            // Error already set by getPkColumnName - add iteration context
            var err_buf: [512]u8 = undefined;
            const prev_err = last_error_buf[0..last_error_len];
            const msg = std.fmt.bufPrint(&err_buf, "iter pk_order={} pk_written={}: {s}", .{ pk_order, pk_written, prev_err }) catch "getPkColumnName failed";
            setLastError(msg);
            return null;
        };
        if (col_name.len == 0) {
            setLastErrorFmt("empty col_name at pk_order={} pk_written={}", .{ pk_order, pk_written });
            return null;
        }
        if (pk_written > 0) {
            select_writer.writeAll(" AND ") catch {
                setLastErrorFmt("failed AND at pos={} pk_order={}", .{ select_fbs.pos, pk_order });
                return null;
            };
        }
        const before_pos = select_fbs.pos;

        select_writer.print("\"{s}\" IS ?", .{col_name}) catch |err| {
            setLastErrorFmt("failed write pk_order={} col_name=[{s}] len={} pos={} err={}", .{ pk_order, col_name, col_name.len, before_pos, err });
            return null;
        };
        const after_pos = select_fbs.pos;
        // Detect if write succeeded but didn't actually write
        if (after_pos == before_pos) {
            setLastErrorFmt("SILENT FAIL: pk_order={} col=[{s}] before_pos={} after_pos={}", .{ pk_order, col_name, before_pos, after_pos });
            return null;
        }
        pk_written += 1;
    }

    const select_len = select_fbs.pos;
    if (select_len >= MAX_SQL_BUF) return null;
    select_buf[select_len] = 0;

    const select_sql: [*:0]const u8 = @ptrCast(&select_buf);

    var select_stmt: ?*api.sqlite3_stmt = null;
    var rc = api.prepare_v2(db, select_sql, -1, &select_stmt, null);
    if (rc != api.SQLITE_OK) {
        const err = api.errmsg(db);
        setLastErrorFmt("SELECT prepare failed (rc={}): {s} | SQL: {s}", .{ rc, std.mem.span(err), std.mem.span(select_sql) });
        return null;
    }
    defer _ = api.finalize(select_stmt);



    for (0..info.pk_count) |i| {
        rc = bindValue(select_stmt, @intCast(i + 1), pk_values[i]);
        if (rc != api.SQLITE_OK) return null;
    }

    rc = api.step(select_stmt);
    if (rc == api.SQLITE_ROW) {
        return api.column_int64(select_stmt, 0);
    }

    // INSERT INTO ... RETURNING __crsql_key
    var insert_buf: [MAX_SQL_BUF]u8 = undefined;
    var insert_fbs = std.io.fixedBufferStream(&insert_buf);
    const insert_writer = insert_fbs.writer();

    insert_writer.print("INSERT INTO \"{s}__crsql_pks\" (", .{table_name}) catch return null;

    pk_order = 1;
    pk_written = 0;
    while (pk_written < info.pk_count) : (pk_order += 1) {
        const col_name = getPkColumnName(info, pk_order) orelse return null;
        if (pk_written > 0) {
            insert_writer.writeAll(", ") catch return null;
        }
        insert_writer.print("\"{s}\"", .{col_name}) catch return null;
        pk_written += 1;
    }

    insert_writer.writeAll(") VALUES (") catch return null;
    for (0..info.pk_count) |i| {
        if (i > 0) insert_writer.writeAll(", ") catch return null;
        insert_writer.writeAll("?") catch return null;
    }
    insert_writer.writeAll(") RETURNING __crsql_key") catch return null;

    const insert_len = insert_fbs.pos;
    if (insert_len >= MAX_SQL_BUF) return null;
    insert_buf[insert_len] = 0;

    var insert_stmt: ?*api.sqlite3_stmt = null;
    const insert_sql: [*:0]const u8 = @ptrCast(&insert_buf);
    rc = api.prepare_v2(db, insert_sql, -1, &insert_stmt, null);
    if (rc != api.SQLITE_OK) {
        const err = api.errmsg(db);
        setLastErrorFmt("INSERT prepare failed (rc={}): {s} | SQL: {s}", .{ rc, std.mem.span(err), std.mem.span(insert_sql) });
        return null;
    }
    defer _ = api.finalize(insert_stmt);

    for (0..info.pk_count) |i| {
        rc = bindValue(insert_stmt, @intCast(i + 1), pk_values[i]);
        if (rc != api.SQLITE_OK) {
            setLastErrorFmt("INSERT bind failed at index {} (rc={})", .{ i + 1, rc });
            return null;
        }
    }

    rc = api.step(insert_stmt);
    if (rc == api.SQLITE_ROW) {
        return api.column_int64(insert_stmt, 0);
    }

    const err = api.errmsg(db);
    setLastErrorFmt("INSERT step failed (rc={}): {s}", .{ rc, std.mem.span(err) });
    return null;
}

fn maybeMarkReinserted(
    db: ?*api.sqlite3,
    table_name: []const u8,
    key: i64,
    db_version: i64,
    seq: i64,
) bool {
    var sql_buf: [1024]u8 = undefined;
    const sql = std.fmt.bufPrintZ(&sql_buf,
        \\UPDATE "{s}__crsql_clock" SET
        \\  col_version = CASE col_version % 2 WHEN 0 THEN col_version + 1 ELSE col_version + 2 END,
        \\  db_version = ?,
        \\  seq = ?,
        \\  site_id = 0
        \\WHERE key = ? AND col_name = ?
    , .{table_name}) catch return false;

    var stmt: ?*api.sqlite3_stmt = null;
    var rc = api.prepare_v2(db, sql, -1, &stmt, null);
    if (rc != api.SQLITE_OK) return false;
    defer _ = api.finalize(stmt);

    rc = api.bind_int64(stmt, 1, db_version);
    if (rc != api.SQLITE_OK) return false;
    rc = api.bind_int64(stmt, 2, seq);
    if (rc != api.SQLITE_OK) return false;
    rc = api.bind_int64(stmt, 3, key);
    if (rc != api.SQLITE_OK) return false;
    rc = api.bind_text(stmt, 4, "-1", 2, api.SQLITE_STATIC);
    if (rc != api.SQLITE_OK) return false;

    rc = api.step(stmt);
    return rc == api.SQLITE_DONE;
}

fn markLocallyUpdated(
    db: ?*api.sqlite3,
    table_name: []const u8,
    key: i64,
    col_name: []const u8,
    db_version: i64,
    seq: i64,
) bool {
    // Mirrors Rust/C mark_locally_updated_stmt
    var sql_buf: [1024]u8 = undefined;
    const sql = std.fmt.bufPrintZ(&sql_buf,
        \\INSERT INTO "{s}__crsql_clock" (
        \\  key, col_name, col_version, db_version, seq, site_id
        \\) SELECT
        \\  ?, ?, 1, ?, ?, 0 WHERE true
        \\ON CONFLICT DO UPDATE SET
        \\  col_version = col_version + 1,
        \\  db_version = ?,
        \\  seq = ?,
        \\  site_id = 0;
    , .{table_name}) catch return false;

    var stmt: ?*api.sqlite3_stmt = null;
    var rc = api.prepare_v2(db, sql, -1, &stmt, null);
    if (rc != api.SQLITE_OK) return false;
    defer _ = api.finalize(stmt);

    rc = api.bind_int64(stmt, 1, key);
    if (rc != api.SQLITE_OK) return false;
    rc = api.bind_text(stmt, 2, @ptrCast(col_name.ptr), @intCast(col_name.len), api.getTransientDestructor());
    if (rc != api.SQLITE_OK) return false;
    rc = api.bind_int64(stmt, 3, db_version);
    if (rc != api.SQLITE_OK) return false;
    rc = api.bind_int64(stmt, 4, seq);
    if (rc != api.SQLITE_OK) return false;
    rc = api.bind_int64(stmt, 5, db_version);
    if (rc != api.SQLITE_OK) return false;
    rc = api.bind_int64(stmt, 6, seq);
    if (rc != api.SQLITE_OK) return false;

    rc = api.step(stmt);
    return rc == api.SQLITE_DONE;
}

fn markRowCreated(
    db: ?*api.sqlite3,
    table_name: []const u8,
    key: i64,
    db_version: i64,
    seq: i64,
) bool {
    // Mirrors Rust/C mark_locally_created_stmt
    var sql_buf: [1024]u8 = undefined;
    const sql = std.fmt.bufPrintZ(&sql_buf,
        \\INSERT INTO "{s}__crsql_clock" (
        \\  key, col_name, col_version, db_version, seq, site_id
        \\) SELECT
        \\  ?, '-1', 1, ?, ?, 0 WHERE true
        \\ON CONFLICT DO UPDATE SET
        \\  col_version = CASE col_version % 2 WHEN 0 THEN col_version + 1 ELSE col_version + 2 END,
        \\  db_version = ?,
        \\  seq = ?,
        \\  site_id = 0
    , .{table_name}) catch return false;

    var stmt: ?*api.sqlite3_stmt = null;
    var rc = api.prepare_v2(db, sql, -1, &stmt, null);
    if (rc != api.SQLITE_OK) return false;
    defer _ = api.finalize(stmt);

    rc = api.bind_int64(stmt, 1, key);
    if (rc != api.SQLITE_OK) return false;
    rc = api.bind_int64(stmt, 2, db_version);
    if (rc != api.SQLITE_OK) return false;
    rc = api.bind_int64(stmt, 3, seq);
    if (rc != api.SQLITE_OK) return false;
    rc = api.bind_int64(stmt, 4, db_version);
    if (rc != api.SQLITE_OK) return false;
    rc = api.bind_int64(stmt, 5, seq);
    if (rc != api.SQLITE_OK) return false;

    rc = api.step(stmt);
    return rc == api.SQLITE_DONE;
}

fn markRowDeleted(
    db: ?*api.sqlite3,
    table_name: []const u8,
    key: i64,
    db_version: i64,
    seq: i64,
) bool {
    // Mirrors Rust/C mark_locally_deleted_stmt
    var sql_buf: [1024]u8 = undefined;
    const sql = std.fmt.bufPrintZ(&sql_buf,
        \\INSERT INTO "{s}__crsql_clock" (
        \\  key, col_name, col_version, db_version, seq, site_id
        \\) SELECT
        \\  ?, '-1', 2, ?, ?, 0 WHERE true
        \\ON CONFLICT DO UPDATE SET
        \\  col_version = 1 + col_version,
        \\  db_version = ?,
        \\  seq = ?,
        \\  site_id = 0
    , .{table_name}) catch return false;

    var stmt: ?*api.sqlite3_stmt = null;
    var rc = api.prepare_v2(db, sql, -1, &stmt, null);
    if (rc != api.SQLITE_OK) return false;
    defer _ = api.finalize(stmt);

    rc = api.bind_int64(stmt, 1, key);
    if (rc != api.SQLITE_OK) return false;
    rc = api.bind_int64(stmt, 2, db_version);
    if (rc != api.SQLITE_OK) return false;
    rc = api.bind_int64(stmt, 3, seq);
    if (rc != api.SQLITE_OK) return false;
    rc = api.bind_int64(stmt, 4, db_version);
    if (rc != api.SQLITE_OK) return false;
    rc = api.bind_int64(stmt, 5, seq);
    if (rc != api.SQLITE_OK) return false;

    rc = api.step(stmt);
    return rc == api.SQLITE_DONE;
}

fn dropNonSentinelClocks(db: ?*api.sqlite3, table_name: []const u8, key: i64) bool {
    var sql_buf: [512]u8 = undefined;
    const sql = std.fmt.bufPrintZ(&sql_buf, "DELETE FROM \"{s}__crsql_clock\" WHERE key = ? AND col_name IS NOT '-1'", .{table_name}) catch return false;

    var stmt: ?*api.sqlite3_stmt = null;
    var rc = api.prepare_v2(db, sql, -1, &stmt, null);
    if (rc != api.SQLITE_OK) return false;
    defer _ = api.finalize(stmt);

    rc = api.bind_int64(stmt, 1, key);
    if (rc != api.SQLITE_OK) return false;

    rc = api.step(stmt);
    return rc == api.SQLITE_DONE;
}

fn moveNonSentinels(db: ?*api.sqlite3, table_name: []const u8, new_key: i64, old_key: i64) bool {
    var sql_buf: [512]u8 = undefined;
    const sql = std.fmt.bufPrintZ(&sql_buf, "UPDATE OR REPLACE \"{s}__crsql_clock\" SET key = ? WHERE key = ? AND col_name != '-1'", .{table_name}) catch return false;

    var stmt: ?*api.sqlite3_stmt = null;
    var rc = api.prepare_v2(db, sql, -1, &stmt, null);
    if (rc != api.SQLITE_OK) return false;
    defer _ = api.finalize(stmt);

    rc = api.bind_int64(stmt, 1, new_key);
    if (rc != api.SQLITE_OK) return false;
    rc = api.bind_int64(stmt, 2, old_key);
    if (rc != api.SQLITE_OK) return false;

    rc = api.step(stmt);
    return rc == api.SQLITE_DONE;
}

// ─────────────────────────────────────────────────────────────────────────────
// SQL UDFs
// ─────────────────────────────────────────────────────────────────────────────

fn crsqlAfterInsertFunc(pCtx: ?*api.sqlite3_context, argc: c_int, argv: [*c]?*api.sqlite3_value) callconv(.c) void {
    if (argc < 2) {
        api.result_error(pCtx, "crsql_after_insert requires table_name and pk values", -1);
        return;
    }

    const db = api.context_db_handle(pCtx);
    const table_name_ptr = api.value_text(argv[0]);
    if (db == null or table_name_ptr == null) {
        api.result_error(pCtx, "crsql_after_insert: invalid args", -1);
        return;
    }
    const table_name = std.mem.span(table_name_ptr.?);

    const info = getTableInfo(db, table_name) orelse {
        var err_buf: [1024]u8 = undefined;
        const err_msg = std.fmt.bufPrintZ(&err_buf, "crsql_after_insert getTableInfo failed: {s}", .{last_error_buf[0..last_error_len]}) catch "crsql_after_insert: failed to get table info";
        api.result_error(pCtx, err_msg.ptr, @intCast(err_msg.len));
        return;
    };

    // Validate we got the expected number of PK columns
    if (info.pk_count == 0) {
        api.result_error(pCtx, "crsql_after_insert: table has no PK columns", -1);
        return;
    }

    const pk_count: usize = @intCast(argc - 1);
    if (pk_count != info.pk_count) {
        api.result_error(pCtx, "crsql_after_insert: PK count mismatch", -1);
        return;
    }

    var pk_values: [64]*api.sqlite3_value = undefined;
    for (0..pk_count) |i| pk_values[i] = argv[i + 1].?;

    const db_version = site_identity.nextDbVersion(null);

    // Get or create the key in __crsql_pks.
    // Note: we intentionally do this before reading current clocks.
    const key_existing = getOrCreatePkKey(db, table_name, &info, pk_values[0..pk_count]) orelse {
        // Return the captured error message with context
        var err_buf: [1024]u8 = undefined;
        const err_msg = std.fmt.bufPrintZ(&err_buf, "crsql_after_insert failed: {s}", .{last_error_buf[0..last_error_len]}) catch "crsql_after_insert: getOrCreatePkKey failed";
        api.result_error(pCtx, err_msg.ptr, @intCast(err_msg.len));
        return;
    };

    if (info.non_pk_count == 0) {
        const seq = site_identity.getNextSeq();
        if (!markRowCreated(db, table_name, key_existing, db_version, seq)) {
            api.result_error(pCtx, "crsql_after_insert: failed to mark created", -1);
            return;
        }
        api.result_int64(pCtx, 0);
        return;
    }

    // If sentinel exists, bump it with maybe_mark_reinserted
    const seq_reinsert = site_identity.getNextSeq();
    _ = maybeMarkReinserted(db, table_name, key_existing, db_version, seq_reinsert);

    // Mark non-PK columns updated
    for (info.columns[0..info.count]) |col| {
        if (col.pk_index == 0) {
            const seq2 = site_identity.getNextSeq();
            if (!markLocallyUpdated(db, table_name, key_existing, col.name[0..col.name_len], db_version, seq2)) {
                api.result_error(pCtx, "crsql_after_insert: failed to mark updated", -1);
                return;
            }
        }
    }

    api.result_int64(pCtx, 0);
}

fn crsqlAfterUpdateFunc(pCtx: ?*api.sqlite3_context, argc: c_int, argv: [*c]?*api.sqlite3_value) callconv(.c) void {
    if (argc < 3) {
        api.result_error(pCtx, "crsql_after_update requires table_name and pk values", -1);
        return;
    }

    const db = api.context_db_handle(pCtx);
    const table_name_ptr = api.value_text(argv[0]);
    if (db == null or table_name_ptr == null) {
        api.result_error(pCtx, "crsql_after_update: invalid args", -1);
        return;
    }
    const table_name = std.mem.span(table_name_ptr.?);

    const info = getTableInfo(db, table_name) orelse {
        api.result_error(pCtx, "crsql_after_update: failed to get table info", -1);
        return;
    };

    const pk_count = info.pk_count;
    const non_pk_count = info.non_pk_count;
    const expected_args: usize = 1 + pk_count * 2 + non_pk_count * 2;
    if (@as(usize, @intCast(argc)) != expected_args) {
        api.result_error(pCtx, "crsql_after_update: argument count mismatch", -1);
        return;
    }

    const pk_new_start: usize = 1;
    const pk_old_start: usize = 1 + pk_count;
    const non_pk_new_start: usize = 1 + pk_count * 2;
    const non_pk_old_start: usize = 1 + pk_count * 2 + non_pk_count;

    var pk_new_values: [64]*api.sqlite3_value = undefined;
    var pk_old_values: [64]*api.sqlite3_value = undefined;

    for (0..pk_count) |i| {
        pk_new_values[i] = argv[pk_new_start + i].?;
        pk_old_values[i] = argv[pk_old_start + i].?;
    }

    const next_db_version = site_identity.nextDbVersion(null);

    const new_key = getOrCreatePkKey(db, table_name, &info, pk_new_values[0..pk_count]) orelse {
        var err_buf: [1024]u8 = undefined;
        const err_msg = std.fmt.bufPrintZ(&err_buf, "crsql_after_update (new_key) failed: {s}", .{last_error_buf[0..last_error_len]}) catch "crsql_after_update: getOrCreatePkKey failed";
        api.result_error(pCtx, err_msg.ptr, @intCast(err_msg.len));
        return;
    };

    var pk_changed = false;
    for (0..pk_count) |i| {
        if (compare_values.compareSqliteValues(pk_new_values[i], pk_old_values[i]) != 0) {
            pk_changed = true;
            break;
        }
    }

    if (pk_changed) {
        const old_key = getOrCreatePkKey(db, table_name, &info, pk_old_values[0..pk_count]) orelse {
            var err_buf: [1024]u8 = undefined;
            const err_msg = std.fmt.bufPrintZ(&err_buf, "crsql_after_update (old_key) failed: {s}", .{last_error_buf[0..last_error_len]}) catch "crsql_after_update: getOrCreatePkKey failed";
            api.result_error(pCtx, err_msg.ptr, @intCast(err_msg.len));
            return;
        };
        const seq_del = site_identity.getNextSeq();
        if (!markRowDeleted(db, table_name, old_key, next_db_version, seq_del)) {
            api.result_error(pCtx, "crsql_after_update: failed to mark deleted", -1);
            return;
        }
        if (!moveNonSentinels(db, table_name, new_key, old_key)) {
            api.result_error(pCtx, "crsql_after_update: failed to move clocks", -1);
            return;
        }
        const seq_create = site_identity.getNextSeq();
        if (!markRowCreated(db, table_name, new_key, next_db_version, seq_create)) {
            api.result_error(pCtx, "crsql_after_update: failed to mark created", -1);
            return;
        }
    }

    // Track non-PK updates
    var non_pk_idx: usize = 0;
    for (info.columns[0..info.count]) |col| {
        if (col.pk_index == 0) {
            const new_val = argv[non_pk_new_start + non_pk_idx].?;
            const old_val = argv[non_pk_old_start + non_pk_idx].?;
            if (compare_values.compareSqliteValues(new_val, old_val) != 0) {
                const seq = site_identity.getNextSeq();
                if (!markLocallyUpdated(db, table_name, new_key, col.name[0..col.name_len], next_db_version, seq)) {
                    api.result_error(pCtx, "crsql_after_update: failed to mark updated", -1);
                    return;
                }
            }
            non_pk_idx += 1;
        }
    }

    api.result_int64(pCtx, 0);
}

fn crsqlAfterDeleteFunc(pCtx: ?*api.sqlite3_context, argc: c_int, argv: [*c]?*api.sqlite3_value) callconv(.c) void {
    if (argc < 2) {
        api.result_error(pCtx, "crsql_after_delete requires table_name and pk values", -1);
        return;
    }

    const db = api.context_db_handle(pCtx);
    const table_name_ptr = api.value_text(argv[0]);
    if (db == null or table_name_ptr == null) {
        api.result_error(pCtx, "crsql_after_delete: invalid args", -1);
        return;
    }
    const table_name = std.mem.span(table_name_ptr.?);

    const info = getTableInfo(db, table_name) orelse {
        api.result_error(pCtx, "crsql_after_delete: failed to get table info", -1);
        return;
    };

    const pk_count: usize = @intCast(argc - 1);
    if (pk_count != info.pk_count) {
        api.result_error(pCtx, "crsql_after_delete: PK count mismatch", -1);
        return;
    }

    var pk_values: [64]*api.sqlite3_value = undefined;
    for (0..pk_count) |i| pk_values[i] = argv[i + 1].?;

    const db_version = site_identity.nextDbVersion(null);
    const seq = site_identity.getNextSeq();

    const key = getOrCreatePkKey(db, table_name, &info, pk_values[0..pk_count]) orelse {
        var err_buf: [1024]u8 = undefined;
        const err_msg = std.fmt.bufPrintZ(&err_buf, "crsql_after_delete failed: {s}", .{last_error_buf[0..last_error_len]}) catch "crsql_after_delete: getOrCreatePkKey failed";
        api.result_error(pCtx, err_msg.ptr, @intCast(err_msg.len));
        return;
    };

    if (!markRowDeleted(db, table_name, key, db_version, seq)) {
        api.result_error(pCtx, "crsql_after_delete: failed to mark deleted", -1);
        return;
    }
    if (!dropNonSentinelClocks(db, table_name, key)) {
        api.result_error(pCtx, "crsql_after_delete: failed to drop clocks", -1);
        return;
    }

    api.result_int64(pCtx, 0);
}

pub fn register(db: ?*api.sqlite3) c_int {
    var rc = api.create_function_v2(
        db,
        "crsql_after_insert",
        -1,
        api.SQLITE_UTF8 | api.SQLITE_INNOCUOUS,
        null,
        &crsqlAfterInsertFunc,
        null,
        null,
        null,
    );
    if (rc != api.SQLITE_OK) return rc;

    rc = api.create_function_v2(
        db,
        "crsql_after_update",
        -1,
        api.SQLITE_UTF8 | api.SQLITE_INNOCUOUS,
        null,
        &crsqlAfterUpdateFunc,
        null,
        null,
        null,
    );
    if (rc != api.SQLITE_OK) return rc;

    rc = api.create_function_v2(
        db,
        "crsql_after_delete",
        -1,
        api.SQLITE_UTF8 | api.SQLITE_INNOCUOUS,
        null,
        &crsqlAfterDeleteFunc,
        null,
        null,
        null,
    );
    return rc;
}
