#!/usr/bin/env bash
# Cross-Platform Sync Compatibility Test
# Verifies wire format compatibility between Zig and Rust/C CR-SQLite implementations
#
# This test ensures that:
# 1. Changes generated by Zig extension can be applied to Rust/C extension
# 2. Changes generated by Rust/C extension can be applied to Zig extension
# 3. pk blob format, site_id, and db_version are compatible
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ZIG_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
REPO_ROOT="$(cd "$ZIG_DIR/.." && pwd)"

echo "=================================================================="
echo "Cross-Platform Sync Compatibility Test"
echo "Zig <-> Rust/C CR-SQLite Wire Format Verification"
echo "=================================================================="
echo ""

# Build the Zig extension
echo "Building Zig extension..."
cd "$ZIG_DIR"
if ! nix run nixpkgs#zig -- build 2>&1; then
    echo "FAIL: Zig build failed"
    exit 1
fi

# Determine extension paths based on platform
if [[ "$(uname)" == "Darwin" ]]; then
    ZIG_EXT="$ZIG_DIR/zig-out/lib/libcrsqlite.dylib"
    # Try multiple locations for Rust/C extension
    if [[ -f "$REPO_ROOT/lib/crsqlite.dylib" ]]; then
        RUST_EXT="$REPO_ROOT/lib/crsqlite.dylib"
    elif [[ -f "$REPO_ROOT/core/dist/crsqlite.dylib" ]]; then
        RUST_EXT="$REPO_ROOT/core/dist/crsqlite.dylib"
    else
        echo "SKIP: Rust/C extension not found (need lib/crsqlite.dylib or core/dist/crsqlite.dylib)"
        echo "Run 'make -C core loadable' or 'npm run bundle-lib' to build it"
        exit 2
    fi
else
    ZIG_EXT="$ZIG_DIR/zig-out/lib/libcrsqlite.so"
    if [[ -f "$REPO_ROOT/lib/crsqlite.so" ]]; then
        RUST_EXT="$REPO_ROOT/lib/crsqlite.so"
    elif [[ -f "$REPO_ROOT/core/dist/crsqlite.so" ]]; then
        RUST_EXT="$REPO_ROOT/core/dist/crsqlite.so"
    else
        echo "SKIP: Rust/C extension not found (need lib/crsqlite.so or core/dist/crsqlite.so)"
        echo "Run 'make -C core loadable' or 'npm run bundle-lib' to build it"
        exit 2
    fi
fi

# Verify extensions exist
if [[ ! -f "$ZIG_EXT" ]]; then
    echo "FAIL: Zig extension not found at $ZIG_EXT"
    exit 1
fi

if [[ ! -f "$RUST_EXT" ]]; then
    echo "SKIP: Rust/C extension not found at $RUST_EXT"
    exit 2
fi

echo "Zig extension:    $ZIG_EXT"
echo "Rust/C extension: $RUST_EXT"
echo ""

# Create temp directory for test databases
TMPDIR=$(mktemp -d)
trap "rm -rf $TMPDIR" EXIT

DB_ZIG="$TMPDIR/db_zig.sqlite"
DB_RUST="$TMPDIR/db_rust.sqlite"
CHANGES_FILE="$TMPDIR/changes.txt"
ERRFILE="$TMPDIR/error.txt"

FAILURES=0

# Helper to run SQL with Zig extension
run_zig() {
    local db="$1"
    local sql="$2"
    nix run nixpkgs#sqlite -- "$db" -cmd ".load $ZIG_EXT" "$sql" 2>"$ERRFILE" || true
}

# Helper to run SQL with Rust/C extension
run_rust() {
    local db="$1"
    local sql="$2"
    nix run nixpkgs#sqlite -- "$db" -cmd ".load $RUST_EXT" "$sql" 2>"$ERRFILE" || true
}

# Check for blocking errors (functions not implemented)
check_blocked() {
    local impl="$1"
    if [[ -s "$ERRFILE" ]]; then
        if grep -q "no such function: crsql_as_crr" "$ERRFILE"; then
            echo "BLOCKED: crsql_as_crr() not implemented in $impl"
            exit 2
        fi
        if grep -q "no such table: crsql_changes" "$ERRFILE"; then
            echo "BLOCKED: crsql_changes virtual table not implemented in $impl"
            exit 2
        fi
        # Show other errors for debugging
        if grep -qiE "(error|Error)" "$ERRFILE"; then
            echo "WARNING: $impl error:"
            cat "$ERRFILE"
        fi
    fi
}

# ══════════════════════════════════════════════════════════════════════════════
# Test A: Zig -> Rust/C Sync
# ══════════════════════════════════════════════════════════════════════════════
echo "=================================================================="
echo "Test A: Zig -> Rust/C Sync"
echo "=================================================================="
echo ""

# Step 1: Create identical schema in both databases
echo "Step 1: Creating CRR schema in both databases..."

run_zig "$DB_ZIG" "
    CREATE TABLE items (id INTEGER PRIMARY KEY NOT NULL, name TEXT, value REAL);
    SELECT crsql_as_crr('items');
"
check_blocked "Zig"

run_rust "$DB_RUST" "
    CREATE TABLE items (id INTEGER PRIMARY KEY NOT NULL, name TEXT, value REAL);
    SELECT crsql_as_crr('items');
"
check_blocked "Rust/C"

echo "PASS: Created schema in both databases"

# Step 2: Insert data in Zig database
echo ""
echo "Step 2: Inserting data in Zig database..."

run_zig "$DB_ZIG" "
    INSERT INTO items VALUES (1, 'apple', 1.50);
    INSERT INTO items VALUES (2, 'banana', 0.75);
    INSERT INTO items VALUES (3, NULL, 2.25);
"
check_blocked "Zig"

ZIG_COUNT=$(run_zig "$DB_ZIG" "SELECT COUNT(*) FROM items;")
if [[ "$ZIG_COUNT" == "3" ]]; then
    echo "PASS: Inserted 3 rows in Zig database"
else
    echo "FAIL: Expected 3 rows in Zig, got: $ZIG_COUNT"
    FAILURES=$((FAILURES + 1))
fi

# Step 3: Get site_ids for filtering
ZIG_SITE_ID=$(run_zig "$DB_ZIG" "SELECT quote(crsql_site_id());")
RUST_SITE_ID=$(run_rust "$DB_RUST" "SELECT quote(crsql_site_id());")

echo ""
echo "Zig site_id:    $ZIG_SITE_ID"
echo "Rust/C site_id: $RUST_SITE_ID"

# Verify site_ids are 16-byte blobs
ZIG_SITE_LEN=$(run_zig "$DB_ZIG" "SELECT length(crsql_site_id());")
RUST_SITE_LEN=$(run_rust "$DB_RUST" "SELECT length(crsql_site_id());")

if [[ "$ZIG_SITE_LEN" == "16" && "$RUST_SITE_LEN" == "16" ]]; then
    echo "PASS: Both site_ids are 16 bytes"
else
    echo "FAIL: site_id length mismatch (Zig=$ZIG_SITE_LEN, Rust=$RUST_SITE_LEN)"
    FAILURES=$((FAILURES + 1))
fi

# Step 4: Export changes from Zig
echo ""
echo "Step 3: Exporting changes from Zig database..."

nix run nixpkgs#sqlite -- "$DB_ZIG" -cmd ".load $ZIG_EXT" "
    SELECT 'CHANGE:' || 
        [table] || '|' || 
        quote(pk) || '|' || 
        cid || '|' || 
        quote(val) || '|' || 
        col_version || '|' || 
        db_version || '|' || 
        quote(site_id) || '|' || 
        cl || '|' || 
        seq
    FROM crsql_changes
    WHERE db_version > 0 AND site_id IS NOT $RUST_SITE_ID;
" > "$CHANGES_FILE" 2>"$ERRFILE"
check_blocked "Zig"

CHANGE_COUNT=$(grep -c "^CHANGE:" "$CHANGES_FILE" || echo "0")
echo "Exported $CHANGE_COUNT change records"

# Debug: show a sample change
echo "Sample change record:"
head -1 "$CHANGES_FILE" | sed 's/CHANGE:/  /'

# Step 5: Apply changes to Rust/C database
echo ""
echo "Step 4: Applying changes to Rust/C database..."

APPLIED=0
while IFS= read -r line; do
    if [[ "$line" == CHANGE:* ]]; then
        change="${line#CHANGE:}"
        IFS='|' read -r tbl pk cid val col_ver db_ver site_id cl seq <<< "$change"
        run_rust "$DB_RUST" "
            INSERT INTO crsql_changes ([table], pk, cid, val, col_version, db_version, site_id, cl, seq)
            VALUES ('$tbl', $pk, '$cid', $val, $col_ver, $db_ver, $site_id, $cl, $seq);
        "
        check_blocked "Rust/C"
        APPLIED=$((APPLIED + 1))
    fi
done < "$CHANGES_FILE"

echo "Applied $APPLIED changes"

# Step 6: Verify data matches
echo ""
echo "Step 5: Verifying data matches..."

ZIG_DATA=$(run_zig "$DB_ZIG" "SELECT id, name, value FROM items ORDER BY id;")
RUST_DATA=$(run_rust "$DB_RUST" "SELECT id, name, value FROM items ORDER BY id;")

echo "Zig data:"
echo "$ZIG_DATA" | sed 's/^/  /'
echo "Rust/C data:"
echo "$RUST_DATA" | sed 's/^/  /'

if [[ "$ZIG_DATA" == "$RUST_DATA" ]]; then
    echo "PASS: Data matches after Zig -> Rust/C sync"
else
    echo "FAIL: Data mismatch after Zig -> Rust/C sync"
    FAILURES=$((FAILURES + 1))
fi

RUST_COUNT=$(run_rust "$DB_RUST" "SELECT COUNT(*) FROM items;")
if [[ "$RUST_COUNT" == "3" ]]; then
    echo "PASS: Rust/C has 3 rows after sync"
else
    echo "FAIL: Expected 3 rows in Rust/C, got: $RUST_COUNT"
    FAILURES=$((FAILURES + 1))
fi

# ══════════════════════════════════════════════════════════════════════════════
# Test B: Rust/C -> Zig Sync
# ══════════════════════════════════════════════════════════════════════════════
echo ""
echo "=================================================================="
echo "Test B: Rust/C -> Zig Sync"
echo "=================================================================="
echo ""

# Step 1: Insert more data in Rust/C database
echo "Step 1: Inserting more data in Rust/C database..."

run_rust "$DB_RUST" "
    INSERT INTO items VALUES (4, 'cherry', 3.00);
    INSERT INTO items VALUES (5, 'date', 4.50);
    UPDATE items SET value = 1.75 WHERE id = 1;
"
check_blocked "Rust/C"

RUST_COUNT=$(run_rust "$DB_RUST" "SELECT COUNT(*) FROM items;")
if [[ "$RUST_COUNT" == "5" ]]; then
    echo "PASS: Rust/C has 5 rows after inserts"
else
    echo "FAIL: Expected 5 rows in Rust/C, got: $RUST_COUNT"
    FAILURES=$((FAILURES + 1))
fi

# Check updated value
RUST_APPLE=$(run_rust "$DB_RUST" "SELECT value FROM items WHERE id = 1;")
echo "Updated apple value in Rust/C: $RUST_APPLE"

# Step 2: Export changes from Rust/C
echo ""
echo "Step 2: Exporting changes from Rust/C database..."

nix run nixpkgs#sqlite -- "$DB_RUST" -cmd ".load $RUST_EXT" "
    SELECT 'CHANGE:' || 
        [table] || '|' || 
        quote(pk) || '|' || 
        cid || '|' || 
        quote(val) || '|' || 
        col_version || '|' || 
        db_version || '|' || 
        quote(site_id) || '|' || 
        cl || '|' || 
        seq
    FROM crsql_changes
    WHERE db_version > 0 AND site_id IS NOT $ZIG_SITE_ID;
" > "$CHANGES_FILE" 2>"$ERRFILE"
check_blocked "Rust/C"

CHANGE_COUNT=$(grep -c "^CHANGE:" "$CHANGES_FILE" || echo "0")
echo "Exported $CHANGE_COUNT change records from Rust/C"

# Step 3: Apply changes to Zig database
echo ""
echo "Step 3: Applying changes to Zig database..."

APPLIED=0
while IFS= read -r line; do
    if [[ "$line" == CHANGE:* ]]; then
        change="${line#CHANGE:}"
        IFS='|' read -r tbl pk cid val col_ver db_ver site_id cl seq <<< "$change"
        run_zig "$DB_ZIG" "
            INSERT INTO crsql_changes ([table], pk, cid, val, col_version, db_version, site_id, cl, seq)
            VALUES ('$tbl', $pk, '$cid', $val, $col_ver, $db_ver, $site_id, $cl, $seq);
        "
        check_blocked "Zig"
        APPLIED=$((APPLIED + 1))
    fi
done < "$CHANGES_FILE"

echo "Applied $APPLIED changes"

# Step 4: Verify data matches
echo ""
echo "Step 4: Verifying data matches..."

ZIG_DATA=$(run_zig "$DB_ZIG" "SELECT id, name, value FROM items ORDER BY id;")
RUST_DATA=$(run_rust "$DB_RUST" "SELECT id, name, value FROM items ORDER BY id;")

echo "Zig data:"
echo "$ZIG_DATA" | sed 's/^/  /'
echo "Rust/C data:"
echo "$RUST_DATA" | sed 's/^/  /'

if [[ "$ZIG_DATA" == "$RUST_DATA" ]]; then
    echo "PASS: Data matches after Rust/C -> Zig sync"
else
    echo "FAIL: Data mismatch after Rust/C -> Zig sync"
    FAILURES=$((FAILURES + 1))
fi

ZIG_COUNT=$(run_zig "$DB_ZIG" "SELECT COUNT(*) FROM items;")
if [[ "$ZIG_COUNT" == "5" ]]; then
    echo "PASS: Zig has 5 rows after sync"
else
    echo "FAIL: Expected 5 rows in Zig, got: $ZIG_COUNT"
    FAILURES=$((FAILURES + 1))
fi

# Verify the update was synced
ZIG_APPLE=$(run_zig "$DB_ZIG" "SELECT value FROM items WHERE id = 1;")
if [[ "$ZIG_APPLE" == "1.75" ]]; then
    echo "PASS: Update to apple (id=1) synced correctly"
else
    echo "FAIL: Update to apple not synced (expected 1.75, got $ZIG_APPLE)"
    FAILURES=$((FAILURES + 1))
fi

# ══════════════════════════════════════════════════════════════════════════════
# Test C: PK Blob Format Compatibility
# ══════════════════════════════════════════════════════════════════════════════
echo ""
echo "=================================================================="
echo "Test C: PK Blob Format Compatibility"
echo "=================================================================="
echo ""

# Create compound PK table in both
DB_ZIG_PK="$TMPDIR/db_zig_pk.sqlite"
DB_RUST_PK="$TMPDIR/db_rust_pk.sqlite"

echo "Testing compound primary key encoding..."

run_zig "$DB_ZIG_PK" "
    CREATE TABLE orders (customer_id INTEGER NOT NULL, order_id INTEGER NOT NULL, amount REAL, PRIMARY KEY (customer_id, order_id));
    SELECT crsql_as_crr('orders');
    INSERT INTO orders VALUES (100, 1, 25.00);
"
check_blocked "Zig"

run_rust "$DB_RUST_PK" "
    CREATE TABLE orders (customer_id INTEGER NOT NULL, order_id INTEGER NOT NULL, amount REAL, PRIMARY KEY (customer_id, order_id));
    SELECT crsql_as_crr('orders');
    INSERT INTO orders VALUES (100, 1, 25.00);
"
check_blocked "Rust/C"

# Get PK encoding from both
ZIG_PK=$(run_zig "$DB_ZIG_PK" "SELECT quote(pk) FROM crsql_changes WHERE [table] = 'orders' LIMIT 1;")
RUST_PK=$(run_rust "$DB_RUST_PK" "SELECT quote(pk) FROM crsql_changes WHERE [table] = 'orders' LIMIT 1;")

echo "Zig PK encoding:    $ZIG_PK"
echo "Rust/C PK encoding: $RUST_PK"

if [[ "$ZIG_PK" == "$RUST_PK" ]]; then
    echo "PASS: PK blob encoding is identical"
else
    echo "FAIL: PK blob encoding differs"
    echo "  Both should encode (100, 1) the same way"
    FAILURES=$((FAILURES + 1))
fi

# ══════════════════════════════════════════════════════════════════════════════
# Test D: db_version Lamport Clock Behavior
# ══════════════════════════════════════════════════════════════════════════════
echo ""
echo "=================================================================="
echo "Test D: db_version Lamport Clock Behavior"
echo "=================================================================="
echo ""

ZIG_VER=$(run_zig "$DB_ZIG" "SELECT crsql_db_version();")
RUST_VER=$(run_rust "$DB_RUST" "SELECT crsql_db_version();")

echo "Zig db_version:    $ZIG_VER"
echo "Rust/C db_version: $RUST_VER"

# Both should have advanced past 0
if [[ "$ZIG_VER" -gt 0 && "$RUST_VER" -gt 0 ]]; then
    echo "PASS: Both db_versions advanced from initial 0"
else
    echo "FAIL: db_version should be > 0 after inserts"
    FAILURES=$((FAILURES + 1))
fi

# After bidirectional sync, versions should reflect received changes
# The receiving side's version should be >= max version it received
echo "INFO: After sync - Zig=$ZIG_VER, Rust/C=$RUST_VER (both should reflect received changes)"

# ══════════════════════════════════════════════════════════════════════════════
# Test E: NULL Value Handling
# ══════════════════════════════════════════════════════════════════════════════
echo ""
echo "=================================================================="
echo "Test E: NULL Value Handling"
echo "=================================================================="
echo ""

# Check that NULL values sync correctly (item 3 has NULL name)
ZIG_NULL=$(run_zig "$DB_ZIG" "SELECT name FROM items WHERE id = 3;")
RUST_NULL=$(run_rust "$DB_RUST" "SELECT name FROM items WHERE id = 3;")

echo "Zig NULL check:    '$ZIG_NULL'"
echo "Rust/C NULL check: '$RUST_NULL'"

# Both should be empty (NULL renders as empty string in CLI)
if [[ -z "$ZIG_NULL" && -z "$RUST_NULL" ]]; then
    echo "PASS: NULL values preserved correctly"
else
    echo "FAIL: NULL value handling differs"
    FAILURES=$((FAILURES + 1))
fi

# ══════════════════════════════════════════════════════════════════════════════
# Test F: Delete Sync
# ══════════════════════════════════════════════════════════════════════════════
echo ""
echo "=================================================================="
echo "Test F: Delete Sync (Tombstone Handling)"
echo "=================================================================="
echo ""

# Delete from Rust/C and sync to Zig
echo "Deleting item 5 from Rust/C..."
run_rust "$DB_RUST" "DELETE FROM items WHERE id = 5;"
check_blocked "Rust/C"

# Export delete change
nix run nixpkgs#sqlite -- "$DB_RUST" -cmd ".load $RUST_EXT" "
    SELECT 'CHANGE:' || 
        [table] || '|' || 
        quote(pk) || '|' || 
        cid || '|' || 
        quote(val) || '|' || 
        col_version || '|' || 
        db_version || '|' || 
        quote(site_id) || '|' || 
        cl || '|' || 
        seq
    FROM crsql_changes
    WHERE db_version > 0 AND site_id IS NOT $ZIG_SITE_ID;
" > "$CHANGES_FILE" 2>"$ERRFILE"

# Apply to Zig
echo "Applying delete to Zig..."
while IFS= read -r line; do
    if [[ "$line" == CHANGE:* ]]; then
        change="${line#CHANGE:}"
        IFS='|' read -r tbl pk cid val col_ver db_ver site_id cl seq <<< "$change"
        run_zig "$DB_ZIG" "
            INSERT INTO crsql_changes ([table], pk, cid, val, col_version, db_version, site_id, cl, seq)
            VALUES ('$tbl', $pk, '$cid', $val, $col_ver, $db_ver, $site_id, $cl, $seq);
        "
    fi
done < "$CHANGES_FILE"

ZIG_COUNT=$(run_zig "$DB_ZIG" "SELECT COUNT(*) FROM items;")
RUST_COUNT=$(run_rust "$DB_RUST" "SELECT COUNT(*) FROM items;")

echo "Zig row count:    $ZIG_COUNT"
echo "Rust/C row count: $RUST_COUNT"

if [[ "$ZIG_COUNT" == "$RUST_COUNT" && "$ZIG_COUNT" == "4" ]]; then
    echo "PASS: Delete synced correctly (4 rows remain)"
else
    echo "FAIL: Delete sync failed (expected 4 rows each)"
    FAILURES=$((FAILURES + 1))
fi

# ══════════════════════════════════════════════════════════════════════════════
# Summary
# ══════════════════════════════════════════════════════════════════════════════
echo ""
echo "=================================================================="
echo "Summary"
echo "=================================================================="
echo ""

if [[ $FAILURES -eq 0 ]]; then
    echo "All cross-platform compatibility tests PASSED"
    echo ""
    echo "Wire format compatibility verified:"
    echo "  - Zig -> Rust/C sync works"
    echo "  - Rust/C -> Zig sync works"
    echo "  - PK blob encoding is identical"
    echo "  - db_version Lamport clock works"
    echo "  - NULL values preserved"
    echo "  - Delete tombstones sync correctly"
    exit 0
else
    echo "$FAILURES test(s) FAILED"
    echo ""
    echo "Compatibility issues found - see failures above"
    exit 1
fi
